[project]
name = "tinbox"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "argparse>=1.4.0",
    "feedparser==6.0.13",
    "feedparser-sgmllib==1.0.0",
]
scripts = { tinbox = "tinbox.__main__:main" }

[dependency-groups]
dev = [
    "pyinstaller>=6.22.0",
    "pytest>=9.1.1",
    "tinbox",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
tinbox = { workspace = true, editable = true }

[tool.uv]
package = true
